apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolchat-front-deployment
spec:
  selector:
    matchLabels:
      app: schoolchat-front
  replicas: 2
  template:
    metadata:
      labels:
        app: schoolchat-front
    spec:
      containers:
        - name: schoolchat-front
          image: schoolchat_front:0.0.1
          ports:
            - containerPort: 80
              name: schoolchatfront