apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-local-pvc
  labels:
    app: dynamodb-local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual