apiVersion: v1
kind: Service
metadata:
  name: schoolchat-back-service
  labels: 
    app: schoolchat-back
spec:
  ports:
    - name: schoolchat-back
      port: 3000
      nodePort: 30780
  type: NodePort
  selector:
    app: schoolchat-back