apiVersion: v1
kind: Service
metadata:
  name: schoolchat-front-service
  labels: 
    app: schoolchat-front
spec:
  ports:
    - name: schoolchat-front
      port: 80
      nodePort: 30100
  type: NodePort
  selector:
    app: schoolchat-front